FROM 192.168.43.10:5002/dockerhub/tomcat:8.5.4-alpine
RUN mkdir /usr/local/tomcat/webapps/javademo
COPY ./javademo/ /usr/local/tomcat/webapps/javademo
#COPY ./run.sh /root/
#EXPOSE 80
#RUN chmod +x /root/run.sh
#CMD ["/root/run.sh"]
